# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='categorytype',
            options={'verbose_name_plural': 'category types'},
        ),
    ]
